### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Beep-Boop-Bopa** [echonet/dynamic#13]
Hey,
   So I downloaded the git and downloaded the data set into a subfolder inside the git. The installation of echonet went fine. But I get this error no matter I try to run any of the given functions. 

![image](https://user-images.githubusercontent.com/42900802/91704583-cc3e5b00-eb49-11ea-9f38-e30bf2cc29ca.png)

I have tried renaming the downloaded folder with the .csv files and the videos, and have also edited that echonet.cfg file. I don't really understand what is going on.

**Comment by douyang** [comment]
This is an issue with file path, please change the .cfg to where you expect the videos. If videos are not present at the expected path, num_samples will return 0.

**Comment by Beep-Boop-Bopa** [comment]
Hey, thanks for the reply and sorry for bothering you so much. I tried two approaches. 
1. So in this git's repo I created a new folder with the name of a4c-video-dir. It has all of the videos.

![image](https://user-images.githubusercontent.com/42900802/92039782-a5e40f80-ed43-11ea-9d08-b74471daf606.png)

I also copy-pasted the two .csv files into this folder

![image](https://user-images.githubusercontent.com/42900802/92039820-b8f6df80-ed43-11ea-8f4c-5eec8cd1757f.png)

But I still get the same error.
![image](https://user-images.githubusercontent.com/42900802/92040097-33276400-ed44-11ea-9f90-9d1151627b32.png)

2. Created another folder with the name of a4c-video-dir which had three items in it: the 2 csv files and a folder named Videos with all the videos in it. Still got the same errors

**Comment by Beep-Boop-Bopa** [comment]
and I also tried these two above methods by editing the echonet.cfg file with a new folder name and tried methods 1,2 described before. Still got the same errors.

**Comment by douyang** [comment]
We've noticed a few errors like this when using a version of pytorch and torchvision different from requirements.txt. Please try using those versions and let us know if still getting that error.

**Comment by Beep-Boop-Bopa** [comment]
Hey,
Thanks a lot for reaching back. I tried to install a conda env. from the requirements given. I did:

**conda create --name Dynamic --file requirements.txt**

But it doesn't work and gives me the following error:
![image](https://user-images.githubusercontent.com/42900802/92952357-d146b880-f42d-11ea-9fc7-5bd62c4ded4d.png)

Do you know how I could resolve this issue?

**Comment by Beep-Boop-Bopa** [comment]
I am trying to do your thing. But need to know something. What is the file/tree structure of the a4c-video-dir? 

For me doing **ls a4c-video-dir** gives **FileList.csv  Videos  VolumeTracings.csv**, where the **Videos** folder contains all of the videos.

**Comment by Beep-Boop-Bopa** [comment]
The issue was resolved. The issue was that in the data provided to us via box, the .csv files that I got had **.avi** after the video file names. Your code for reading the videos assumes that they didn't have **.avi** after the video file names.

**Comment by douyang** [comment]
Thanks so much for the update! We will update the CSV to reflect that.

**Comment by atanuGuin** [comment]
@Beep-Boop-Bopa, could you please let me know your echonet.cfg configuration? I have deleted '.avi' part from FIlelist.csv but still getting the same error. All the videos and 2 csv files are kept at path:
**/workspace/xxx/yyy/dynamic/a4c-video-dir**
and my echonet.cfg containes the DATA_DIR path as follows:
**(my_syft_env) root@380b6b959170:/workspace/xxx/yyy/dynamic# cat echonet.cfg
DATA_DIR =/workspace/xxx/yyy/dynamic/a4c-video-dir/**

Thanks in advance.

**Comment by Beep-Boop-Bopa** [comment]
In my experience, the echonet.cfg file thing doesn't really work that well. So I am not using it at all. I don't have a .config file. The python file which does **"import echonet"** is in the same directory as a4c-video-dir. 


Right now, my code has .avi in it and is working. I dunno why.

**Comment by Beep-Boop-Bopa** [comment]
Just try with and without the .avi extension in the csv files and see what works.

**Comment by chinmayabv** [comment]
Hi Im running into some issues and unable to figure out the contents of the csv file. Can you please provide me with a sample FileList.csv or the headers that need to be in it?
![Screenshot from 2021-04-23 21-35-26](https://user-images.githubusercontent.com/35324931/115944554-1202b780-a47c-11eb-8756-1ac726670586.png)

**Comment by chahalinder0007** [comment]
@chinmayabv The sample csv looks like this:

```
Filename,EF,ESV,EDV,FrameHeight,FrameWidth,FPS,Frame,Split
0X100009310A3BD7FC.avi,78.49840597,14.88136797,69.21053366,112,112,50,174,VAL
0X1002E8FBACD08477.avi,59.10198811,40.38387624,98.74288352,112,112,50,215,TRAIN
0X1005D03EED19C65B.avi,62.36379841,14.2677839,37.90973395,112,112,50,104,TRAIN
0X10075961BC11C88E.avi,54.54509675,33.14308352,72.91420979,112,112,55,122,TRAIN
0X10094BA0A028EAC3.avi,24.88774165,127.5819446,169.8550242,112,112,52,207,VAL
0X100CF05D141FF143.avi,55.95179045,47.45383119,107.7315779,112,112,50,248,TEST
0X100E3B8D3280BEC5.avi,36.57373876,81.74728111,128.8855429,112,112,38,101,TRAIN
0X100E491B3CD58DE2.avi,33.99174499,76.86556916,116.4484187,112,112,50,226,TRAIN
0X100F044876B98F90.avi,69.31525203,25.13140943,81.90195812,112,112,50,221,TRAIN
```

**Comment by SumiranRai** [comment]
C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=R2Plus1D_18_Weights.KINETICS400_V1`. You can also use `weights=R2Plus1D_18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:11<00:00, 12.00s/it]
100%|██████████| 1/1 [00:13<00:00, 13.26s/it]

0it [00:00, ?it/s]
0it [00:15, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\sumir\AppData\Roaming\Python\Python312\Scripts\echonet.exe\__main__.py", line 7, in <module>
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\echonet\utils\video.py", line 185, in run
    loss, yhat, y = echonet.utils.video.run_epoch(model, dataloader, phase == "train", optim, device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\echonet\utils\video.py", line 358, in run_epoch
    yhat = np.concatenate(yhat)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate

How to resolve this error?


FileName,EF,ESV,EDV,FrameHeight,FrameWidth,FPS,NumberOfFrames,Split
0X100009310A3BD7FC,78.49840597,14.88136797,69.21053366,112,112,50,174,TRAIN
0X1002E8FBACD08477,59.10198811,40.38387624,98.74288352,112,112,50,215,TRAIN
0X1005D03EED19C65B,62.36379841,14.2677839,37.90973395,112,112,50,104,TRAIN
0X10075961BC11C88E,54.54509675,33.14308352,72.91420979,112,112,55,122,TRAIN
0X10094BA0A028EAC3,24.88774165,127.5819446,169.8550242,112,112,52,207,VAL

sample filelist.csv

FileName,X1,Y1,X2,Y2,Frame
0X100009310A3BD7FC.avi,51.26041667,15.34895833,64.93229167,69.125,46
0X100009310A3BD7FC.avi,50.03761083,17.16784126,53.36722189,16.32132997,46
0X100009310A3BD7FC.avi,49.15737821,20.40762939,57.09054885,18.3907216,46
0X100009310A3BD7FC.avi,48.5381733,23.58105455,59.99733911,20.66770731,46
0X100009310A3BD7FC.avi,47.91896839,26.7544797,62.90412937,22.94469301,46
0X100009310A3BD7FC.avi,47.9621045,29.75951307,65.81091963,25.22167871,46
0X100009310A3BD7FC.avi,48.16791529,32.72318847,68.24704281,27.61832554,46
0X100009310A3BD7FC.avi,48.37372608,35.68686387,70.38531105,30.0906982,46
0X100009310A3BD7FC.avi,48.57953687,38.65053927,72.5235793,32.56307085,46
0X100009310A3BD7FC.avi,49.01403934,41.55607271,74.15164369,35.16515635,46
0X100009310A3BD7FC.avi,49.83099892,44.3643713,75.71299787,37.78420208,46
0X100009310A3BD7FC.avi,50.64795851,47.17266989,77.27435205,40.4032478,46
0X100009310A3BD7FC.avi,51.4649181,49.98096847,78.64469427,43.07085589,46
0X100009310A3BD7FC.avi,52.54732826,52.72177963,79.48537463,45.87312377,46
0X100009310A3BD7FC.avi,53.7042693,55.44364225,80.326055,48.67539165,46
0X100009310A3BD7FC.avi,54.36563,58.29149988,80.609375,51.61936132,46
0X100009310A3BD7FC.avi,51.15135239,62.12468928,80.609375,54.63536149,46
0X100009310A3BD7FC.avi,49.33671909,65.6020369,80.4312144,57.69665674,46
0X100009310A3BD7FC.avi,50.3482871,68.36085877,80.06545076,60.80564767,46
0X100009310A3BD7FC.avi,57.51297555,69.55532799,79.69968713,63.9146386,46
0X100009310A3BD7FC.avi,71.93835296,68.90385933,79.33392349,67.02362953,46
0X100009310A3BD7FC.avi,56.0,19.54166667,61.65104167,62.74479167,61
0X100009310A3BD7FC.avi,55.61529756,20.69577397,57.09330327,20.50244833,61

sample volume
tracing.csv
